#page title
page_title                                :      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1584776704                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : fr                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apple-store/id1584776704?pt=123480917&ct=www&mt=8     # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :            # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Sambot helps all members of a Mobile App Development Team (Developers, Designers, DevOps, Q&A, Product Manager...) to be more productive, reactive and efficient while using Bitrise CI services 🚀

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Sambot app is a faithful companion helping you in your Bitrise continuous integration experience, to be more efficient on what you love to do!
# Sambot is a tool helping you and all members of your team (Developers, DevOps, Q&A, PO/PM, Designers) to be more productive while using Bitrise Continuous Integration service

# Information About Yourself
your_name                                 : Jay & Jay                                
your_link                                 : https://jaynjay.app                     
your_city                                 : Paris                                
email_address                             : sambot-public1021@jaynjay.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : sambot_app
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  : 

  - title                                 : Projects
    description                           : Quick access to your most important projects to follow their health and builds at any time
    fontawesome_icon_name                 : star

  - title                                 : Workflows
    description                           : Add all recurrent workflows (for any combination of projects, branches, or tags) to your Dashboard and run them at a glance
    fontawesome_icon_name                 : layer-group

  - title                                 : Builds
    description                           : Monitor all details of any builds from any projects and restart or abord them in one tap
    fontawesome_icon_name                 : cogs

  - title                                 : Analytics Insight
    description                           : Get lots of charts from your projects statistics about their cost, build status, duration and more...
    fontawesome_icon_name                 : chart-line

  - title                                 : Steps
    description                           : Follow workflows steps (live or afterward) parsed from Bitrise log to instantly identify what's happening
    fontawesome_icon_name                 : shoe-prints

  - title                                 : Easy Artifacts download
    description                           : Download all your builds artifacts easily
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Automatic Artifacts updates
    description                           : Mark any artifacts as favorite and always get the last updated version of them on your Dashboard
    fontawesome_icon_name                 : save

  - title                                 : Notifications
    description                           : Receive a push notification as soon as a build is finished (in success or in error) and act in the nick of time
    fontawesome_icon_name                 : bell

  - title                                 : Easy to Use
    description                           : Find the build you are looking for with a powerful search engine to inspect, re-run or abort it instantly
    fontawesome_icon_name                 : check-circle

  - title                                 : Error Analysis
    description                           : Helps you to quickly understand why and where your build has failed
    fontawesome_icon_name                 : exclamation-triangle

  - title                                 : Siri & Shortcut support
    description                           : Launch your favorite workflows/builds with Shortcut & Siri
    fontawesome_icon_name                 : microphone

  - title                                 : Tests Report
    description                           : Get a comprehensive & understandable parsed test report summary for your builds
    fontawesome_icon_name                 : bug

  - title                                 : iCloud Sync
    description                           : All your favorite projects, workflows, and custom environment parameters are synchronized all over your devices
    fontawesome_icon_name                 : cloud

  - title                                 : Live Update
    description                           : Sambot app auto-refresh when builds start or finish without any manual action to always allow you to be as reactive as possible
    fontawesome_icon_name                 : bolt

  - title                                 : Project Weather
    description                           : See your projects trends through a nice weather forecast representation
    fontawesome_icon_name                 : cloud-moon-rain

  - title                                 : Easy to Configure
    description                           : Intuitive onboarding and easy access to the most useful features
    fontawesome_icon_name                 : tools

  - title                                 : Dark Mode Support 
    description                           : Choose the one you love to work with
    fontawesome_icon_name                 : adjust

  # - title                                 : Performances
  #   description                           : Fast, Responsive and light app (download size < 10 MB)
  #   fontawesome_icon_name                 : tachometer-alt

  - title                                 : Favorites builds
    description                           : Save build configuration for quick redo
    fontawesome_icon_name                 : redo

  - title                                 : Bitrise live log themes
    description                           : Build logs from Bitrise are parsed and colorized with themes
    fontawesome_icon_name                 : terminal

  - title                                 : Project customisation
    description                           : Customize your projects with tens of colors
    fontawesome_icon_name                 : palette

  - title                                 : Security & Privacy
    description                           : All private information is encrypted and protected from the outside world
    fontawesome_icon_name                 : shield-alt

  - title                                 : Modern code
    description                           : iOS 15 support, 100% SwiftUI (Composable Architecture), and backend written in Swift
    fontawesome_icon_name                 : code


#Find icons on fontawesome.com/icons

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.5
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header_sambot2.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.75

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#4B6DC2"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#333333"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#4B6DC2"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#4B6DC2"

footer_text_color                         : "#4B6DC2"

# feature_icons_foreground_color            : "#1d63ea"
# feature_icons_background_color            : "#e6e6e6"
# social_icons_foreground_color             : "#666666"
# social_icons_background_color             : "#e6e6e6"
# footer_text_color                         : "#666666"







####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
